# Generated by Django 4.0.6 on 2022-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_det',
            name='alternateno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='ln',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='marital',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp_det',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_det',
            name='fn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
