# Generated by Django 4.0.6 on 2022-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_emp_det_alternateno_emp_det_bg_emp_det_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_det',
            name='alternateno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_det',
            name='bg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_det',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_det',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_det',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emp_det',
            name='marital',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_det',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
